import { Button, VerticalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    in-out property<string> start_time: "00:00:00";
    in-out property<string> end_time: "00:00:00";
    in-out property <string> input_file: "No file selected";
    callback clip_video();

    VerticalBox {
        GridLayout{
            Row{
                Text {
                    text: "Start Time:";
                }

                new_start_time := TextInput {
                    text: "00:00:00";
    
                    edited => {
                        root.start_time = new_start_time.text;
                    }
                }
            }
            Row{
                Text {
                    text: "End Time:";
                }
                new_end_time := TextInput {
                    text: "00:00:00";
    
                    edited => {
                        root.end_time = new_end_time.text;
                    }
                }
            }
            Row{
                Text {
                    text: "File Name:";
                }
                new_input_file := TextInput {
                    text: "";
    
                    edited => {
                        root.input_file = new_input_file.text;
                    }
                }
            }
        }
        Button {
            text: "Start Clip";
            clicked => {
                root.clip_video();
            }
        }
    }
}